#!/bin/bash

ports="8080 8181 8282"
tests="Empty 1024"

rm -rf *.out Report-* Reports.zip

for port in $ports
do
	for test in $tests
	do
		echo "Test ${test} on port ${port}"
		~/apache-jmeter-5.0/bin/jmeter.sh -Jport=${port} -n -t Request-${test}.jmx -l Request-${test}.${port}.out -e -o ./Report-${test}-${port}/
		echo "Pausing..."
		sleep 5
	done
done

echo "Zipping Reports.zip"
zip -r Reports.zip Report-*
