#!/bin/bash

export JVM_ARGS="-Xms4g -Xmx4g"

ports=${1:-"8181 8282 8383 8585 8686 8787 8888 8989 9000"}
tests=${2:-"getArgs2048"}

for port in $ports
do
	for test in $tests
	do
		echo "Test ${test} on port ${port}"
		rm -rf Report-${test}-${port} Report-${test}-${port}.zip Request-${test}.${port}.out Request-${test}.${port}.out.zip
		~/apache-jmeter-5.0/bin/jmeter.sh -Gport=${port} -Guri=${test} -n -t Request-getArgs2048.jmx -R10.252.133.10,10.252.133.11,10.252.133.12 -l Request-${test}.${port}.out -e -o ./Report-${test}-${port}/ \
			&& \
		echo "Zipping Report-${test}-${port}.zip" && zip -r Report-${test}-${port}.zip Report-${test}-${port} \
			&& \
		echo "Zipping Request-${test}.${port}.out.zip" && zip -r Request-${test}.${port}.out Request-${test}.${port}.out.zip \
			&& \
		rm -rf Report-${test}-${port} Request-${test}.${port}.out
	done
done
