#!/bin/bash

set -e

export JVM_ARGS="-Xms1g -Xmx1g"

ports=${1:-"8181 8282 8383 8585 8686 8787 8888 8989 9000"}
tests=${2:-"empty 2048 8192"}
jmx=${3:-"Request-Generic.jmx"}
minions=${4:-"-R10.252.133.11,10.252.133.12,10.252.133.13"}

for port in $ports
do
	for test in $tests
	do
		echo "Test ${test} on port ${port} with ${jmx}"
		rm -f Results-${test}-${port}*.csv \
			Results-${test}-${port}*.zip
		
		startTime=`date +%s`
		
		JVM_ARGS="-Xms6g -Xmx6g" HEAP="-Xms6g -Xmx6g -XX:MaxMetaspaceSize=256m" ~/apache-jmeter-5.0/bin/jmeter.sh \
			-Jport=${port} -Juri=${test} \
			-Gport=${port} -Guri=${test} -n \
			-t ${jmx} ${minions} \
			-l Results-${test}-${port}.csv || exit 1
		
		endTime=`date +%s`		
		
		echo "Zipping Results-${test}-${port}.csv.zip" && \
		zip Results-${test}-${port}.csv.zip Results-${test}-${port}.csv && \
		rm Results-${test}-${port}.csv
		
		psql -q -h ubuntuvm -U zabbix -d zabbix <<<"copy(
			select clock, value 
			from history 
			where itemid=28504 and clock between ${startTime} and ${endTime}
			order by clock desc) 
			to stdout with csv header;" > Results-${test}-${port}.cpu.csv
		echo "Zipping Results-${test}-${port}.cpu.csv.zip" && \
		zip Results-${test}-${port}.cpu.csv.zip Results-${test}-${port}.cpu.csv && \
		rm Results-${test}-${port}.cpu.csv
		
	done
done
