#!/bin/bash

JVM_ARGS="-Xms1024m -Xmx1024m"

ports="8080 8181 8282 8383 8484 8585"
tests="empty 1024 2048 4096 8192"

rm -rf *.out Report-* Reports.zip

for port in $ports
do
	for test in $tests
	do
		echo "Test ${test} on port ${port}"
		~/apache-jmeter-5.0/bin/jmeter.sh -Jport=${port} -Juri=${test} -n -t Request-Generic.jmx -l Request-${test}.${port}.out -e -o ./Report-${test}-${port}/
		echo "Pausing..."
		sleep 5
	done
done

echo "Zipping Reports.zip"
zip -r Reports.zip Report-*
