#!/bin/bash

set -e

if [ $1 == "all" ]
then
	keys=`./list`
	for key in ${keys}
	do
		./$0 ${key} &
	done
	wait
else
	label=$1
	title=`echo ${label} | tr _ " "`
	./exportcsv ${label} ./tmp/Results-${label}
	gnuplot \
		-e "successfile='./tmp/Results-${label}.success.csv'" \
		-e "failurefile='./tmp/Results-${label}.failure.csv'" \
		-e "title='\"${title}\" Request Total Time'" \
		-c plot-elapsed.gnu > Charts/Results-${label}.elapsed.png
	gnuplot \
		-e "successfile='./tmp/Results-${label}.success.csv'" \
		-e "failurefile='./tmp/Results-${label}.failure.csv'" \
		-e "title='\"${title}\" Requests Per Second'" \
		-c plot-hits.gnu > Charts/Results-${label}.hits.png
fi
echo complete