#!/bin/bash

set -e

uncache=${2:-""}

if [ $1 == "all" ]
then
	keys=`./list`
	for key in ${keys}
	do
		./$0 ${key} &
	done
	wait
else
	label=$1
	if [[ ! -z $uncache ]]
	then
		rm -f ./tmp/Results-${label}.*.csv
	fi
	title=`echo ${label} | tr _ " "`
	./exportcsv ${label} ./tmp/Results-${label}
	gnuplot \
		-e "successfile='./tmp/Results-${label}.success.csv'" \
		-e "failurefile='./tmp/Results-${label}.failure.csv'" \
		-e "title2='\"${title}\" Request Total Time'" \
		-e "title1='\"${title}\" Requests Per Second'" \
		-c plot-elapsed.gnu > Charts/Results-${label}.pdf
fi
echo complete