#!/bin/bash
# import jmeter results csv file into postgres
set -e

input=$1
label=$2
tableName=${label}
psql -U postgres -d cengn -c "CREATE TABLE IF NOT EXISTS ${tableName} (LIKE request INCLUDING ALL)"
psql -U postgres -d cengn -c "DELETE FROM ${tableName};"
ProcessCSV/ProcessCSV ${input} ${label} | psql -U postgres -d cengn -c "COPY ${tableName} FROM stdin csv header;"
