#!/bin/bash
# import jmeter results csv.zip file into postgres
set -e

input=$1
cpufile=$2
label=$3
cpubase=`basename ${cpufile}`

tableName=${label}
psql -U postgres -d cengn -c "CREATE TABLE IF NOT EXISTS ${tableName} (LIKE request INCLUDING ALL)"
psql -U postgres -d cengn -c "TRUNCATE ${tableName};"
unzip -q -c "${cpufile}" > "/tmp/${cpubase}"
unzip -q -c "${input}" | \
	./ProcessCSV/ProcessCSV "${label}" "/tmp/${cpubase}" | \
	psql -U postgres -d cengn -c "COPY ${tableName} FROM stdin csv header;"
