disabled_rules:
  - trailing_whitespace
  - void_return
  - generic_type_name
  - class_delegate_protocol
  - identifier_name
  - weak_delegate
included:
  - Sources
line_length: 150
function_body_length:
  warning: 50
  error: 75
